<div class="card my-4">
    <h5 class="card-header">Search</h5>
    <div class="card-body">
        <form action="/search" method="post">
            <div class="input-group">
                <input type="text" name="searchName" class="form-control" placeholder="Search for...">
                <span class="input-group-append">
                    <button class="btn btn-secondary" type="submit">Go!</button>
                </span>
            </div>
        </form>
    </div>
</div>